# Backend values for PROD environment
# Updated manually or via approved pipeline

backend:
  replicaCount: 1
  image:
    repository: tejasdesai27/todo-backend
  tag: main-39
    pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  env:
    FLASK_ENV: production
    SECRET_KEY: prod-secret-key-CHANGEME
    DATABASE_URL: postgresql://todouser:todopass@postgres:5432/todos
