# Frontend values for PROD environment
# Updated manually or via approved pipeline

frontend:
  replicaCount: 1
  image:
    repository: tejasdesai27/todo-frontend
    tag: bf27defe-f6cc-46a1-9780-3f98dc1bc7d9
    pullPolicy: Always
  resources:
    requests:
      cpu: 20m
      memory: 96Mi
    limits:
      cpu: 300m
      memory: 256Mi
  env:
    SECRET_KEY: prod-secret-key-CHANGEME
    BACKEND_API_URL: http://backend:5000
    FEATURE_DUE_DATE: "true"
    FEATURE_DARK_MODE: "false"
    CASK_API_KEY: "f479b8e5-6683-4a15-864f-33def5f2c333"
