# Backend values for DEV environment
# Updated automatically by CBCI pipeline

backend:
  replicaCount: 1
  image:
    repository: tejasdesai27/todo-backend
    tag: 636f3b82-2e30-459a-9368-38b3c6caa6a3
    pullPolicy: Always
  env:
    FLASK_ENV: development
    SECRET_KEY: dev-secret-key
    DATABASE_URL: postgresql://todouser:todopass@postgres:5432/todos
