# Backend values for DEV environment
# Updated automatically by CBCI pipeline

backend:
  replicaCount: 1
  image:
    repository: tejasdesai27/todo-backend
    tag: 89de3ae0-2d31-4060-949f-ade3b8c1d77e
    pullPolicy: Always
  env:
    FLASK_ENV: development
    SECRET_KEY: dev-secret-key
    DATABASE_URL: postgresql://todouser:todopass@postgres:5432/todos
