# Frontend values for DEV environment
# Updated automatically by CBCI pipeline

frontend:
  replicaCount: 1
  image:
    repository: tejasdesai27/todo-frontend
    tag: 21bc5130-3df8-4c99-8c10-84be2d664fd6
    pullPolicy: Always
  env:
    SECRET_KEY: dev-secret-key
    BACKEND_API_URL: http://backend:5000
    FEATURE_DUE_DATE: "true"
    FEATURE_DARK_MODE: "true"
    CASK_API_KEY: "716e8e9b-eb22-4df4-aacf-818f035db116"
