# Backend values for QA environment
# Updated automatically by CBCI pipeline

backend:
  replicaCount: 1
  image:
    repository: tejasdesai27/todo-backend
    tag: main-45
    pullPolicy: Always
  env:
    FLASK_ENV: production
    SECRET_KEY: qa-secret-key-replace
    DATABASE_URL: postgresql://todouser:todopass@postgres:5432/todos
