# Frontend values for QA environment
# Updated automatically by CBCI pipeline

frontend:
  replicaCount: 1
  image:
    repository: tejasdesai27/todo-frontend
    tag: main-2
    pullPolicy: Always
  env:
    SECRET_KEY: qa-secret-key-replace
    BACKEND_API_URL: http://backend:5000/api
    FEATURE_DUE_DATE: "true"
    FEATURE_DARK_MODE: "true"
