# Frontend values for QA environment
# Updated automatically by CBCI pipeline

frontend:
  replicaCount: 1
  image:
    repository: tejasdesai27/todo-frontend
    tag: main-5
    pullPolicy: Always
  env:
    SECRET_KEY: qa-secret-key-replace
    BACKEND_API_URL: http://backend:5000
    FEATURE_DUE_DATE: "true"
    FEATURE_DARK_MODE: "true"
    CASK_API_KEY: "0d230090-64e4-45d8-8621-8eaae8d55989"
