apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dev-todo-app
type: Opaque
stringData:
  POSTGRES_USER: todouser
  POSTGRES_PASSWORD: todopass
  POSTGRES_DB: todos
  DATABASE_URL: postgresql://todouser:todopass@postgres-service:5432/todos
